### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by achilleus68** [skoef/ha-zonnepanelendelen#4]
I am not getting any results from the integration. I see the following in the logfile:

```
Logger: homeassistant.config_entries
Source: custom_components/zonnepanelendelen/__init__.py:29
Integration: Zonnepanelendelen ([documentation](https://github.com/skoef/ha-zonnepanelendelen), [issues](https://github.com/skoef/ha-zonnepanelendelen/issues))
First occurred: 2 juni 2023 om 21:33:45 (1 occurrences)
Last logged: 2 juni 2023 om 21:33:45
Error setting up entry zonnepanelendelen for zonnepanelendelen

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/zonnepanelendelen/__init__.py", line 29, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

I am running on 

```
Home Assistant 2023.5.4 
Supervisor 2023.04.1 
Operating System 10.2 
Frontend-versie: 20230503.3 - latest 
```

**Comment by skoef** [comment]
Strange, I'm running similar versions and I can't reproduce these issues. Which logfile are you seeing these messages in?
```
Home Assistant 2023.6.0
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230607.0 - latest
```

**Comment by achilleus68** [comment]
Settings > System > Log (Instellingen > Systeem > Logboek)
This is the latest entry

```
Logger: homeassistant.config_entries
Source: custom_components/zonnepanelendelen/__init__.py:29
Integration: Zonnepanelendelen ([documentation](https://github.com/skoef/ha-zonnepanelendelen), [issues](https://github.com/skoef/ha-zonnepanelendelen/issues))
First occurred: 19:06:22 (5 occurrences)
Last logged: 20:01:48
Error setting up entry zonnepanelendelen for zonnepanelendelen

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zonnepanelendelen/__init__.py", line 29, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by achilleus68** [comment]
Reinstalling the integration did not solve the issue. I can add un/pw and then it says connected, but still no data and the same error in the log

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/zonnepanelendelen/__init__.py:29
Integration: Zonnepanelendelen (documentation, issues)
First occurred: 19:06:22 (6 occurrences)
Last logged: 20:10:02

Error setting up entry zonnepanelendelen for zonnepanelendelen
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zonnepanelendelen/__init__.py", line 29, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

```

**Comment by achilleus68** [comment]
Maybe this is related?

https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

```
Before 2022.8, it was impossible to await config entry platforms forwards without a deadlock if one of the platforms loaded by the config entry was not already loaded.

Integrations need to be refactored to replace calls to hass.config_entries.async_setup_platforms with hass.config_entries.async_forward_entry_setups and/or await all hass.config_entries.async_forward_entry_setup to ensure that Home Assistant does not inadvertently reload the integration while entities and platforms are still being set up.
```

**Comment by achilleus68** [comment]
Ok, that definitely was the issue. Somehow my version had `hass.config_entries.async_setup_platforms` instead of `hass.config_entries.async_forward_entry_setups` in `./custom_components/zonnepanelendelen/__init__.py`

Changing that line made the integration work again. 

Very strange since I only installed the integration last december.
